# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XCodeTest' do
  use_frameworks!
  target 'XCodeTestUITests' do
    puts "checking env"
    puts ENV["cpt_cached"]
    if ENV["cpt_cached"] == "true"
        puts "using cached"
  	    pod 'mParticle-Cross-Platform/Api', :git => 'https://github.com/mParticle/crossplatform-sdk-tests.git'
            pod 'mParticle-Cross-Platform/Models', :git => 'https://github.com/mParticle/crossplatform-sdk-tests.git'
            pod 'mParticle-Cross-Platform/Mocking', :git => 'https://github.com/mParticle/crossplatform-sdk-tests.git'
            pod 'mParticle-Cross-Platform/Testing', :git => 'https://github.com/mParticle/crossplatform-sdk-tests.git'
            pod 'mParticle-Cross-Platform/Tests', :git => 'https://github.com/mParticle/crossplatform-sdk-tests.git'
            pod 'mParticle-Apple-SDK', '~> 8'
  	 else
  	    puts "using local"
  	    pod 'Tests', :path => '../../../Tests'
    end
  end

end
